#contains the functions to help smooth a path generated by rrt sfc bspline class
from rrt_mavsim.message_types.msg_waypoints import MsgWaypoints_SFC
from rrt_mavsim.message_types.msg_world_map import MsgWorldMap
from rrt_mavsim.message_types.msg_waypoints import MsgWaypoints_SFC
from rrt_mavsim.message_types.msg_safeFlightCorridor import Msg_SFC
import numpy as np

#defines helper function to get positions pairs list
def getPositionsPairsList(waypoints_not_smooth: MsgWaypoints_SFC):

    #gets all the positions in the corridor list
    corridorPositions_list = waypoints_not_smooth.getAllPositions()
    #gets  the length of the corridor positions list
    corridorPositions_len = len(corridorPositions_list)

    #creates the list of pairs of positions
    positionsPairs_list = []

    indices_list = []

    #section to get all the combinations of the positions list
    for i in range(corridorPositions_len - 1):

        #gets the start position
        start_position = corridorPositions_list[i]

        #then iterates over the positions after i
        for j in range((i + 1), corridorPositions_len):

            end_position = corridorPositions_list[j]

            #creates the tuple and saves it
            tempList = [start_position, end_position]

            positionsPairs_list.append(tempList)

            indices_list.append([i,j])

    return positionsPairs_list, indices_list




#helper function to get the valid positions and indices list from all the pairs
def getValidPositionsPairs(positionsPairs_list: list[list[np.ndarray]],
                           indicesPairs_list: list[list[int]],
                           world_map: MsgWorldMap,
                           initialWidth: float):


        validPositions_list = []
        validIndices_list = []
        #creates a corresponding flight corridor list
        flightCorridor_list = []

        #creates the corresponding cost list
        cost_list = []

        intersectionDetected_list = []

        #iterates over each position pair in the list
        for positionPair, indicesPair in zip(positionsPairs_list, indicesPairs_list):

            #gets the start position
            startPosition = positionPair[0]
            endPosition = positionPair[1]

            #gets the start index and end index
            startIndex = indicesPair[0]
            endIndex = indicesPair[1]

            #creates the corridor
            tempCorridor = MsgFlightCorridor(primaryPosition=startPosition,
                                             secondaryPosition=endPosition,
                                             primaryPosition_index=startIndex,
                                             secondaryPosition_index=endIndex,
                                             initialTotalWidth=initialWidth)

            #gets the length of the temp corridor, from the primary to the secondary position
            tempCorridor_cost = tempCorridor.primaryToSecondary_distance

            
            #call the intersection detected map
            tempCorridor_intersectionDetected = intersectionDetected(corridor=tempCorridor,
                                                                     world_map=world_map)

            intersectionDetected_list.append(tempCorridor_intersectionDetected)

            if not tempCorridor_intersectionDetected:

                validPositions_list.append(positionPair)
                validIndices_list.append(indicesPair)
                flightCorridor_list.append(tempCorridor)

                #appends the cost
                cost_list.append(tempCorridor_cost)
        
        return validPositions_list, validIndices_list, flightCorridor_list, cost_list



#creates the convex hull intersection function
def intersectionDetected(corridor: MsgFlightCorridor,
                         world_map: MsgWorldMap):
    
    #gets the vertices of the corridor
    corridorVertices = corridor.getVerticesList()
    
    #gets the list of convex hulls from this thing
    obstacleConvexHulls = world_map.getConvexHullList()

    #gets the buffered convex hull from the corridor vertices 
    bufferedConvexHull = (MultiPoint(corridorVertices).convex_hull).buffer(1e-9)
    
    intersectionOccurred = False

    #iterates over each obstacle and checks whether a collision has occurred
    for obstacleHull in obstacleConvexHulls:
        #calls the function to get whether a temporary intersection occurred
        tempIntersectionOccurred = bufferedConvexHull.intersects(obstacleHull)
        
        #if there is an intersection, we break out
        if tempIntersectionOccurred:
            intersectionOccurred = True
            break

    #returns whether there was an intersection
    return intersectionOccurred
